### ISSUE TITLE
run problom

### ISSUE THREAD

**Issue by KwongFuk** [monarch-initiative/malco#45]
(malco-py3.11) PS C:\Users\92529\Desktop\Rare\malco> pheval run -i myinputdirectory -r "malcorunner" -o myoutputdirectory -t tests
could not load template
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\92529\AppData\Local\pypoetry\Cache\virtualenvs\malco-DSIf-2zD-py3.11\Scripts\pheval.exe\__main__.py", line 7, in <module>
  File "C:\Users\92529\AppData\Local\pypoetry\Cache\virtualenvs\malco-DSIf-2zD-py3.11\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\92529\AppData\Local\pypoetry\Cache\virtualenvs\malco-DSIf-2zD-py3.11\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\92529\AppData\Local\pypoetry\Cache\virtualenvs\malco-DSIf-2zD-py3.11\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\92529\AppData\Local\pypoetry\Cache\virtualenvs\malco-DSIf-2zD-py3.11\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\92529\AppData\Local\pypoetry\Cache\virtualenvs\malco-DSIf-2zD-py3.11\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\92529\AppData\Local\pypoetry\Cache\virtualenvs\malco-DSIf-2zD-py3.11\Lib\site-packages\pheval\cli_pheval.py", line 87, in run
    runner_class = get_implementation_resolver().lookup(runner)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\92529\AppData\Local\pypoetry\Cache\virtualenvs\malco-DSIf-2zD-py3.11\Lib\site-packages\class_resolver\api.py", line 176, in lookup
    return get_cls(
           ^^^^^^^^
  File "C:\Users\92529\AppData\Local\pypoetry\Cache\virtualenvs\malco-DSIf-2zD-py3.11\Lib\site-packages\class_resolver\api.py", line 378, in get_cls
    raise KeyError(
KeyError: "Invalid PhEvalRunner name: malcorunner (normalized to: malcorunner). Valid choices are: ['defaultphevalrunner']"
(malco-py3.11) PS C:\Users\92529\Desktop\Rare\malco>

**Comment by leokim-l** [comment]
Hi @KwongFuk , thanks for pointing this out. The code is very much a work in progress. I have a feeling the error above may be related to poetry and setup, e.g. what happens with a pull, poetry update?

If you are interested further in the code let me know!
Also, be aware of this line of code:

https://github.com/monarch-initiative/malco/blob/1e70ff6ea138000d369638965c9cf30099f6f266/pyproject.toml#L17
